sphinx:
  configuration: docs/conf.py
build:
  image: latest
python:
  version: 3.7
  install:
    - requirements: docs/requirements.txt
    - requirements: requirements.txt
    - method: pip
      path: .
      extra_requirements:
          - docs
    - method: setuptools
      path: package
  system_packages: true
